# Generated by Django 4.0.4 on 2022-05-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('totalInkomst', models.IntegerField(blank=True, default=0, null=True)),
                ('totalUtgift', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DagligaUtgifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.theday')),
            ],
        ),
        migrations.CreateModel(
            name='DagligaInkomster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('name', models.CharField(default='no', max_length=150)),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='budget.klient')),
                ('the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.theday')),
            ],
        ),
    ]
