# Generated by Django 4.0.4 on 2022-04-27 21:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 4, 27))),
            ],
        ),
        migrations.CreateModel(
            name='DagligaUtgifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.theday')),
            ],
        ),
        migrations.CreateModel(
            name='DagligaInkomster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('klient', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.theday')),
            ],
        ),
    ]
